# Generated by Django 3.1.3 on 2021-02-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210115_2344'),
        ('chat', '0002_auto_20210125_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author2',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='accounts.profile'),
        ),
    ]
