# Generated by Django 3.1.3 on 2021-02-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210115_2344'),
        ('chat', '0003_auto_20210205_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='accounts.profile'),
        ),
    ]
