# Generated by Django 3.1.3 on 2021-01-05 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suggestions',
            field=models.ManyToManyField(blank=True, related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
