# Generated by Django 3.1.3 on 2021-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='suggestions',
            field=models.ManyToManyField(blank=True, related_name='_profile_suggestions_+', to='accounts.Profile'),
        ),
    ]
