# Generated by Django 3.1.3 on 2021-01-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210105_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='suggestions',
        ),
    ]
